#!/bin/sh

if [ "${0##*/}" = shrc ]; then
    PARENT="$(d=${0%/*}/; [ "_$d" = "_$0/" ] && d='./'; cd "$d."; pwd)"
else
    PARENT="${HOME}/.shell"
fi

for _file in $(find "${PARENT}/init.d" -name '*.sh' | sort); do
    SOURCE_PATH="${_file}" . "${_file}"
done
